### ISSUE TITLE
strict mode disables block parameters

### ISSUE THREAD

**Issue by olsonpm** [handlebars-lang/handlebars.js#1459]
Before filing issues, please check the following points first:

- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

----

[jsfiddle](https://jsfiddle.net/9D88g/740/)

I don't see anything regarding block parameters not working in strict mode, and I can't think of a reason for why they would be disabled.

I wanted to be sure this was a bug and not my misunderstanding before I created a PR with a failing test-case

**Comment by mlaccetti** [comment]
Well, I just spent a few days running against the wall, only to find this bug. I'm assuming it is a bug, because if this is a feature, I'm full of sadness.

**Comment by nknapp** [comment]
I think it is a bug. Any help in resolving it is appreciated

**Comment by jaylinski** [comment]
Fixed by https://github.com/handlebars-lang/handlebars.js/pull/1855.
