### ISSUE TITLE
uglify-js is always downloaded on compatible environments

### ISSUE THREAD

**Issue by Silic0nS0ldier** [handlebars-lang/handlebars.js#1488]
This isn't #1391 but it does have some overlap. The work done towards resolving that issue only permits functionality when `uglify-js` isn't available.

This issue here is related to how NPM treats optional dependencies. Namely, it treats them as dependencies that the package can work without, but would like to have if possible (e.g. `chokidar` has an optional dependency on `fsevents` to permit better file system event handling on unix systems).

To make `uglify-js` truly optional, it should be a `peerDependency`. This expresses compatibility without having it automatically installed, leaving the dependency up to whoever uses handlebars.

Happy to make a PR for this (including any updates that would be needed for testing, etc) if people are happy with the proposed change.

**Comment by nknapp** [comment]
I'd like to see this in 5.0, because anyone who uses Handlebars in a pure Node.js-environment, actually does not need uglify at all.

**Comment by Silic0nS0ldier** [comment]
I'll take a look and see if I can get a PR together then.

**Comment by nknapp** [comment]
That's great. Please make sure to use the master-branch as target branch for the merge request.

**Comment by Silic0nS0ldier** [comment]
PR is up. Let me know if there are any questions or concerns.
