### ISSUE TITLE
Compile spec with webpack/babel

### ISSUE THREAD

**Issue by nknapp** [handlebars-lang/handlebars.js#1512]
The tests  (in the "spec" directory) are not compiled with babel, but only concatenated before they are loaded. This means, that no ES6-syntax is possible, as long as SauceLabs-tests are run with IE10, IE11 and older Safari-versions.

This happened in #1497.

Tests should also be compiled with babel to prevent such errors in the future.

**Comment by jaylinski** [comment]
All modern browsers support ES6 syntax now and we moved from SauceLabs to Playwright, so closing.
