### ISSUE TITLE
[Docs] Where can I get v3.0.7 minified for use in browser?

### ISSUE THREAD

**Issue by vfonic** [handlebars-lang/handlebars.js#1546]
- [x] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

----

I'm trying to find minified handlebars v3.0.7 to use on my site. I checked the installation page: http://handlebarsjs.com/installation.html
There I found S3 builds page. But I could only find v3.0.5 for v3.x versions.
I found on jsdelivr and cdnjs v3.0.7, but I don't know which version should I download/link-to in my html page?

https://www.jsdelivr.com/package/npm/handlebars?version=3.0.7&path=dist

https://cdnjs.com/libraries/handlebars.js/3.0.7

Perhaps, since loading libraries in browsers is still a thing 😆, it could be written somewhere in the documentation?

Thanks!

**Comment by nknapp** [comment]
I would use https://cdn.jsdelivr.net/npm/handlebars@3.0.7/dist/handlebars.min.js or https://cdn.jsdelivr.net/npm/handlebars@3.0.7/dist/handlebars.runtime.min.js depending on whether you need the compiler of just the runtime.

Something must have gone wrong with the build so that they have not been uploaded to AWS. 

I actually wasn't aware that loading libraries in the browser is still a thing and for production setup, you should really use webpack, parcel or browserify to load you templates and the runtime.

If you would like to add a PR for updating the documentation in that respect, you are welcome to do that here: https://handlebars-draft.knappi.org/topics/installation.html#javascript-browser

**Comment by vfonic** [comment]
Thanks @nknapp!

I didn't know the difference between `handlebars.min.js` and `handlebars.runtime.min.js`. I'm pretty sure I don't need the compiler, but just the runtime on my website.

Thanks again! I'll close this issue as it's been solved.

**Comment by nknapp** [comment]
I'll reopen this as a reminder to add docs

**Comment by papasmile** [comment]
@nknapp it looks like you made that compile/runtime distinction already in https://github.com/handlebars-lang/docs/commit/1e2930254e37f17559d0e0104baecce5a2d473d8

Looks nice... Should this issue be closed?

**Comment by nknapp** [comment]
The issue for the docs is that there is no download-link for the 3.x version. But I'll move this issuce over to the docs (if I can).

**Comment by papasmile** [comment]
Oh, ok you mean like just a "Download Previous Version" section after that one? https://handlebarsjs.com/installation/#latest-release-version-handlebarsversions-latest

Also, getting 403 Unauthorized trying to open S3 https://com.s3.amazonaws.com/builds.handlebarsjs/bucket-listing.html?sort=lastmod&sortdir=desc

Also, tried hitting https://s3.amazonaws.com/builds.handlebarsjs.com/handlebars-v3.0.7.js and get 'The specified key does not exist.' ... but cloud flare works ok https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.7/handlebars.js

**Comment by nknapp** [comment]
For some reason, the following URL does not work:

> https://com.s3.amazonaws.com/builds.handlebarsjs/bucket-listing.html?sort=lastmod&sortdir=desc 

while the corresponding URL on 

> http://builds.handlebarsjs.com.s3.amazonaws.com/bucket-listing.html?sort=lastmod&sortdir=desc 

does work. But with the second version, we don't get https...

**Comment by nknapp** [comment]
Ah, I see:  The URL should be 

> http://s3.amazonaws.com/builds.handlebarsjs.com/bucket-listing.html?sort=lastmod&sortdir=desc

but bucket-listing.html contains a javascript that still uses the wrong endpoint to load the listing data. I have to see if I can upload a new one.

**Comment by jaylinski** [comment]
:information_source: There is now a dependabot configuration: https://github.com/handlebars-lang/handlebars.js/blob/master/.github/dependabot.yml

**Comment by jaylinski** [comment]
We have uploaded a new downloads page which includes all handlebars versions and linked it on our docs site:

https://s3.amazonaws.com/builds.handlebarsjs.com/
