### ISSUE TITLE
How to limit posts on Handlebars?

### ISSUE THREAD

**Issue by naseebbajracharya** [handlebars-lang/handlebars.js#1652]
Before filing issues, please check the following points first:

- [ ] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [ ] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

**Comment by papasmile** [comment]
Also, how about a stale-bot? https://github.com/marketplace/stale

**Comment by nknapp** [comment]
@naseebbajracharya do you mean: How do we get less issues in Handlebars? Or do you have a question on how to use Handlebars?

**Comment by jaylinski** [comment]
@naseebbajracharya If this is still relevant, please start a discussion in the "Q&A"-category: https://github.com/handlebars-lang/handlebars.js/discussions/categories/q-a
