### ISSUE TITLE
[Help]How handlebars handles property not found situation?

### ISSUE THREAD

**Issue by royIdoodle** [handlebars-lang/handlebars.js#1680]
```javascript
const Handlebars = require('handlebars');

function replaceTemplate(content, options) {
  return Handlebars.compile(content.toString())(options);
}


const result = replaceTemplate('hi, {{ user }} {{ project }}', { project: 'demo' });

assert(replaceTemplate('hi, {{ user }} {{ project }}', { project: 'demo' }) === 'hi, {{ user }} demo');
```

What I expect is when some `name` in template is not found, it could be ignored, like `{{ somename }}`, not compiled into `empty string`.

What can I do to achieve this situation?

`helperMissing` is not what I want, code below has side effect. It does not ignore the name, it forces to rewrite the template.
```javascript
Handlebars.registerHelper('helperMissing', function(context) {
  return `{{ ${context.name} }}`;
});
```

*Advices*

 * return more info in `context`, like code below. With `origin` value, I can use helperMissing Handler to fix it.
```javascript
    { lookupProperty: [Function: lookupProperty],
  name: 'user',
  hash: {},
  origin: `{{ user }}`
  data: { root: { project: 'demo', key: null } },
  loc:
   { start: { line: 1, column: 4 }, end: { line: 1, column: 14 } } }
 ```
 * register ignore key, so I can walk the options structure, and decide with key should be ignored.

**Comment by jaylinski** [comment]
@royIdoodle If this is still relevant, please start a discussion in the "Q&A"-category: https://github.com/handlebars-lang/handlebars.js/discussions/categories/q-a
