### ISSUE TITLE
Expecting 'ID', got 'INVALID'

### ISSUE THREAD

**Issue by snowy1000** [handlebars-lang/handlebars.js#1685]
I get the following error when I try to use code belove:
This is the code I use: `<div class="text-dark font-weight-bold h5 mb-0"><span>{{bot.users.cache.get("300573341591535617")}}</span></div>`

Error is: `Expecting 'ID', got 'INVALID'`

Note: I allowed proto methods by using this library: `@handlebars/allow-prototype-access`. Also I downgraded Handlebars version to 4.5.3 but still getting this error.

**Comment by snowy1000** [comment]
Output of `{{log bot.users.cache}}` is: https://hasteb.in/ageyaxin.yaml

**Comment by nknapp** [comment]
Have a look at the docs... You cannot use JavaScript inside the mustaches. I think removing the brackets might be enough though

**Comment by snowy1000** [comment]
But I need to use it as a method. I also looked at the docs.

Do you have a solution/workaround?

**Comment by nknapp** [comment]
The Handlebars way is to register a helper to implement that functionally. And you can pass parameters to that helper in the template. But as I said, removing the brackets might work as well:

```
{{bot.users.cache.get "300573341591535617"}}
```
