### ISSUE TITLE
Typo on Installation page

### ISSUE THREAD

**Issue by endepointe** [handlebars-lang/handlebars.js#1689]
Typo can be found at: https://handlebarsjs.com/guide/#installation, underneath the 
Installation title.

"The fastest way to test Handlebars is to use into load it from a CDN and and embed it in an HTML file."

should read: 

"The fastest way to test Handlebars is to load it from a CDN and embed it in an HTML file."

**Comment by siddhantk232** [comment]
This issue can be closed as this is fixed :)
