### ISSUE TITLE
AST to template

### ISSUE THREAD

**Issue by pinturic** [handlebars-lang/handlebars.js#1691]
I have a particular task so what I need to do is:

1. getting the AST from the template
1. make many manipulations to the AST
1. **transforming the AST back to a handlebars template**

Is there any way to transform the AST to a template?

**Comment by nknapp** [comment]
Yes, see this document: https://github.com/handlebars-lang/handlebars.js/blob/master/docs/compiler-api.md

Maybe we should move this document to the documentation website...

**Comment by nknapp** [comment]
Sorry, I just wrote an answer, but then I saw that I misread the question. You should be able to do so by implementing a [visitor](https://github.com/handlebars-lang/handlebars.js/blob/master/docs/compiler-api.md#ast-visitor), but I don't think that there is an existing visitor that already does that.

**Comment by pinturic** [comment]
I have built min AST2Template visitor starting from the printer https://github.com/handlebars-lang/handlebars.js/blob/master/lib/handlebars/compiler/printer.js.

It is almost complete and working correctly; if it is meaningful for you and needed I can make a PR
