### ISSUE TITLE
escaping html strings

### ISSUE THREAD

**Issue by dhirajforyou** [handlebars-lang/handlebars.js#1699]
here is the template

`<li class="result_description">`
    `{{{description}}}`
`</li>`

If description is html string and has unclosed tags in it, its messing UI.
ex. `<p>Product</li> <li>Round</li>  <li>strap</li> ....`
Here `<p>Product</li>` is going to close `<li class="result_description">`

Is There any support in handlebars to generate a node element first and then append as child ?
Any other inputs are highly appreciated

**Comment by jaylinski** [comment]
You have to either strip the HTML or ensure that the HTML is valid.

If `{{{description}}}` is user input, you will have an XSS vulnerability on your site.

**Comment by dhirajforyou** [comment]
@jaylinski 
Thanks for inputs and sorry for being to late to update here. its not going to be user input.

I got some references but haven't implemented though.
https://stackoverflow.com/questions/494143/creating-a-new-dom-element-from-an-html-string-using-built-in-dom-methods-or-pro/35385518#35385518

**Comment by dhirajforyou** [comment]
Yes, XSS vulnerability will be an issue here.
Closing this issue.
