### ISSUE TITLE
Using handlebars as ES6 module on the browser

### ISSUE THREAD

**Issue by camilonova** [handlebars-lang/handlebars.js#1707]
Before filing issues, please check the following points first:

- [X] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [X] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [X] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [X] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

Hi. I'm trying to do this:

```
import '../node_modules/jquery/dist/jquery.min.js';
import '../node_modules/jquery-validation/dist/jquery.validate.min.js';
import '../node_modules/jquery-validation/dist/additional-methods.min.js';
import '../node_modules/handlebars/dist/handlebars.runtime.js';

console.log(Handlebars.VERSION);
```

Is throwing this error:

```
handlebars.runtime.js:35 Uncaught TypeError: Cannot set property 'Handlebars' of undefined
    at webpackUniversalModuleDefinition (handlebars.runtime.js:35)
    at handlebars.runtime.js:36
```

I'm not using webpack, just trying to use native ES6 modules at the browser.

**Comment by camilonova** [comment]
I ended up using webpack

**Comment by softmarshmallow** [comment]
Doesn't work on webpack either. (for me)

`Cannot read property 'Handlebars'`

**Comment by capaj** [comment]
@camilonova handlebars don't work in webpack too. See https://github.com/handlebars-lang/handlebars.js/issues/953
