### ISSUE TITLE
import * as Handlebars from "handlebars/runtime" to register custom helpers

### ISSUE THREAD

**Issue by fdiluzio** [handlebars-lang/handlebars.js#1711]
refers to: https://github.com/handlebars-lang/handlebars.js/issues/1553

I need to import Handlebars differently when using custom helpers.
I'm using webpack.

The fiddle works as expected:
https://jsfiddle.net/5jpc9obu/

My handlebars 4.7.6 package.json is:
"browser": {
".": "./dist/cjs/handlebars.js",
"./runtime": "./dist/cjs/handlebars.runtime.js"
},

I import Handlebars in a class like this when I register a helper. Otherwise the helper is missing.
import * as Handlebars from "handlebars/runtime";

However, my entry point js uses Handlebar.compile and that only works when I import like this:
import Handlebars from 'handlebars';

My distributed js file, however, remains the same size even with the two different imports.

**Comment by sophiebl** [comment]
Here is a work around solution for this with` Object.assign()`:

```
import MainHandlebars from "handlebars";
import * as RuntimeHandlebars from "handlebars/runtime";
const Handlebars = Object.assign(MainHandlebars, RuntimeHandlebars);
```

**Comment by fdiluzio** [comment]
Interesting. I'll have to consider that the next time I visit my code.
