### ISSUE TITLE
Mustache and hbs parameter differentiation.

### ISSUE THREAD

**Issue by ghost** [handlebars-lang/handlebars.js#1715]
I am using Mustache and Handlebars simultaneously for views and templates. The problem doing so is that if I use {{parameter}} in .hbs file then how do i make sure that this parameter is rendered with Mustache in client side JS and not via res.render in server side.

The default behaviour is that the hbs file assumes that this {{parameter}} is sent from server side handlebars rendereing and if i actually sent this from Mustache and not server side handlebars then it appears null.

Thanks.

**Comment by jaylinski** [comment]
If this is still relevant, please start a discussion in the "Q&A"-category: https://github.com/handlebars-lang/handlebars.js/discussions/categories/q-a
