### ISSUE TITLE
2 questions need developer support

### ISSUE THREAD

**Issue by vuongtrankimmy** [handlebars-lang/handlebars.js#1718]
1. I load the list more than 30 item, the display speed is quite slow (About **30 seconds / 30 items**). Can the developer test and solve this problem for me?

2. I have used the function **{{#if}} .... {{else}} .... {{/ if}}**. to handle html block. The if value (1 or true). But the handler that only runs at **{{else}}** cannot do **{{if}}** (In my if function there is **attribute / class**). I don't know if it's my code error or what the problem. Thanks to the dev to help me.

**Comment by jaylinski** [comment]
If this is still relevant, please start a discussion in the "Q&A"-category: https://github.com/handlebars-lang/handlebars.js/discussions/categories/q-a
