### ISSUE TITLE
Upgrading HandlebarJS to v 4.7.6 from   v3.0.3

### ISSUE THREAD

**Issue by asklimetech** [handlebars-lang/handlebars.js#1719]
Could you please help me to understand, does upgrading Handlebarjs V3.0.3 to V4.7.6 will cause any backward compatibility issue or any other issues?
As the Project size too big,  so just want to be more careful before upgrading the version.

Thanks.

**Comment by savelevcorr** [comment]
Hi!
Actually, there are few breaking changes descripted in the release list.
Please, inspect this [file](https://github.com/handlebars-lang/handlebars.js/blob/master/release-notes.md) for those changes and make a decision.
