### ISSUE TITLE
@last not set to true when there is one element

### ISSUE THREAD

**Issue by marikaner** [handlebars-lang/handlebars.js#1721]
Before filing issues, please check the following points first:

- [ ] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [ ] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

Hi,

the `@last` data variable is not set to true for arrays with only one element:
```
[
{{#each items}}
  {{item}}{{#unless @last}},{{/unless}}
{{/each}}
]
```
results in:
```
[
  item,
]
```

For more than one element this works just fine.

**Comment by jaylinski** [comment]
Seems to be fixed now: https://jsfiddle.net/etf8qb64/
