### ISSUE TITLE
Question, Escape block on server rendering to execute on the browser

### ISSUE THREAD

**Issue by nmocruz** [handlebars-lang/handlebars.js#1724]
Hi,

I was thinking in render with html templates with express, but the some content they should be escaped, like script tags and template tags,
So the idea is my view could have a html template that could be fully escaped

```{{serverProcess.name}}
<template id='client-template' >
  Hi, am a browser template, maybe reactivejs
  {{message}}
</tempale>

<script>
const ractive = Ractive({
  el: 'body',
  data: {
    message: 'Hello World!'
  },
 template: document.getElementById('client-template')
})
</script>```

**Comment by nknapp** [comment]
I would advise against this. You can escape tags with a backslash, but this will quickly become unreadable and unmaintainable.

Did you know that Ractive also supports server-side rendering? Maybe you should try that instead 
https://ractive.js.org/concepts/#server-side

And as someone who has worked with Ractive before and seen other things as well, I would like to advise: 

It you are just setting up a new project: Don't use Ractive. If you like the template syntax, use Vue.js. It's very similar, but Vue has a much larger active community and way better integration into IDEs and tools for testing etc. At least a couple of years ago, it was like that.
