### ISSUE TITLE
Unexpected token errors.   

### ISSUE THREAD

**Issue by TheiChrist** [handlebars-lang/handlebars.js#1725]
* [ ] This is NOT a security issues!! If it is, please file a report at https://www.npmjs.com/advisories/report?package=handlebars**

Bug description:says unexpected token 

Example link

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22Carolyn%5CnBornn%5Cnp%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%22%7D%5D%2C%22input%22%3A%22firstname%3ACarolyn%5Cnlastname%3ABornn%5Cn%5Cn%22%2C%22output%22%3A%22%3Cp%3E%20%3C%2Fp%3E%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper%5Cnloudfunction(string)%20%7B%5Cnreturn%20string.toUpperCase()%5Cn%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.5%22%7D

# Expected outcome

# Actual outcome

**Comment by nknapp** [comment]
I don't know what you want to achieve, but your preparationscript needs to be valid javascript and your input needs to be JSON.

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22Carolyn%5CnBornn%5Cnp%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%22%7D%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%5C%22Carolyn%5C%22%2C%5Cn%5Ctlastname%3A%5C%22Bornn%5C%22%5Cn%7D%5Cn%5Cn%22%2C%22output%22%3A%22Carolyn%5CnBornn%5Cnp%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper(%5C%22loud%5C%22%2C%20function(string)%20%7B%5Cn%5Ctreturn%20string.toUpperCase()%5Cn%7D)%5Cn%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.5%22%7D
