### ISSUE TITLE
Allow dynamic array items

### ISSUE THREAD

**Issue by roipoussiere** [handlebars-lang/handlebars.js#1735]
It is possible to retrieve the third array element with `items.[2]`, but it seems not possible to do the same thing with a dynamic value, for instance `items.[@index]`.

It could be interesting to loop over several arrays at the same time, such as:

```js
// data = {numbers: ['zero', 'one', 'two'], values: ['foo', 'bar', 'baz']}
<ul>{{#each values}}<li> {{.}}: {{@index}} -> {{@root.numbers.[@index]}}</li>{{/each}}</ul>
```

Test code: https://jsfiddle.net/t9njfw5v/1/

It can be achieved with this helper: 

```js
Handlebars.registerHelper('get', function(array, i) {return array[i]});
```

but it's less practical.

**Comment by peepo5** [comment]
why is this not a thing?

**Comment by jaylinski** [comment]
This already works via [`lookup`](https://handlebarsjs.com/guide/builtin-helpers.html#lookup): `{{lookup ../numbers @index}}`

Example: https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%3Cul%3E%5Cn%7B%7B%23each%20values%7D%7D%5Cn%5Ct%3Cli%3E%20%7B%7B.%7D%7D%3A%20%7B%7B%40index%7D%7D%20-%3E%20%7B%7Blookup%20..%2Fnumbers%20%40index%7D%7D%3C%2Fli%3E%5Cn%7B%7B%2Feach%7D%7D%5Cn%3C%2Ful%3E%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20numbers%3A%20%5B'zero'%2C%20'one'%2C%20'two'%5D%2C%5Cn%20%20values%3A%20%5B'foo'%2C%20'bar'%2C%20'baz'%5D%5Cn%7D%22%2C%22output%22%3A%22%3Cul%3E%5Cn%5Ct%3Cli%3E%20foo%3A%200%20-%3E%20zero%3C%2Fli%3E%5Cn%5Ct%3Cli%3E%20bar%3A%201%20-%3E%20one%3C%2Fli%3E%5Cn%5Ct%3Cli%3E%20baz%3A%202%20-%3E%20two%3C%2Fli%3E%5Cn%3C%2Ful%3E%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D
