### ISSUE TITLE
Change step value depending of the amount

### ISSUE THREAD

**Issue by rodcoiler** [handlebars-lang/handlebars.js#1750]
Hi, I just wanted to ask a favor, if someone would be kind enough to tell me how to change the value of step if the bar exceeds 30000 in amount.
The step is set to 1000, but I would like to know how to add a variable when the bar reaches 30,000, automatically change the step value to 10000 or 5000.
Thank you

**Comment by jaylinski** [comment]
If this is still relevant, please start a discussion in the "Q&A"-category: https://github.com/handlebars-lang/handlebars.js/discussions/categories/q-a
