### ISSUE TITLE
Helper value not resolved

### ISSUE THREAD

**Issue by stevemk14ebr** [handlebars-lang/handlebars.js#1759]
Hello, I'm having an issue with custom helpers. My helper is getting the name of the key unresolved, instead of the value as expected when using a certain key style.

My helper is simple:
```
HandleBars.registerHelper('truncate', (context, arg1) => {
    if (!context) {
        return `INVALID_HANDLEBARS_PLACEHOLDER`;
    }
    let val = context.substring(0, arg1);
    return new HandleBars.SafeString(val);
});
```

I use this like this (and it works):
```
sample with MD5 hash {{{md5}}} ({{{truncate md5 6}}}...)
```

This however fails and just gives me the key (File.md5). So the truncation of the value fails and returns File.m instead of the shortened hash.
```
{{{"Characteristics.original filename"}}} ({{{truncate "File.md5" 6}}})
```

My json for the second is valid, and does render just fine without the truncate helper being used. I'm also not sure why quotes are required but I had to do this to get it to work:
![image](https://user-images.githubusercontent.com/6619205/122072151-5304b180-cdc5-11eb-8d37-62e491f8aea4.png)

Renders as:
![image](https://user-images.githubusercontent.com/6619205/122072643-c3133780-cdc5-11eb-99b9-cabf23e82f9d.png)

**Comment by stevemk14ebr** [comment]
The issue is with the json path implementation. It's trying to access the fields as json path but fails since they are not nested json but rather keys with json path style, it should probably try the key access first?

**Comment by jaylinski** [comment]
You can use a literal reference: `sample with MD5 hash {{{"file.md5"}}} ({{{truncate [file.md5] 6}}}...)`

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22sample%20with%20MD5%20hash%20%7B%7B%7B%5C%22file.md5%5C%22%7D%7D%7D%20(%7B%7B%7Btruncate%20%5Bfile.md5%5D%206%7D%7D%7D...)%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20%5C%22file.md5%5C%22%3A%20%5C%2201fac3c905f81ca51ea0a9ab3f302ee4%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22sample%20with%20MD5%20hash%2001fac3c905f81ca51ea0a9ab3f302ee4%20(01fac3...)%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('truncate'%2C%20(context%2C%20arg1)%20%3D%3E%20%7B%5Cn%20%20%20%20if%20(!context)%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%60INVALID_HANDLEBARS_PLACEHOLDER%60%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20let%20val%20%3D%20context.substring(0%2C%20arg1)%3B%5Cn%20%20%20%20return%20new%20Handlebars.SafeString(val)%3B%5Cn%7D)%3B%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D
