### ISSUE TITLE
Helper in Handlebars

### ISSUE THREAD

**Issue by Amlleluzzz** [handlebars-lang/handlebars.js#1768]
* [ ] This is NOT a security issues!! If it is, please file a report at https://www.npmjs.com/advisories/report?package=handlebars**

# Example link

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23ifCond%20v1%20v2%7D%7D%5Cn%20%20%20%20%7B%7Bv1%7D%7D%20is%20equal%20to%20%7B%7Bv2%7D%7D%5Cn%7B%7Belse%7D%7D%5Cn%20%20%20%20%7B%7Bv1%7D%7D%20is%20not%20equal%20to%20%7B%7Bv2%7D%7D%5Cn%7B%7B%2FifCond%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%20v1%3A%5C%22aaa%5C%22%2Cv2%3A%5C%22bbb%5C%22%20%7D%5Cn%22%2C%22output%22%3A%22%20%20%20%20aaa%20is%20not%20equal%20to%20bbb%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('ifCond'%2C%20function(v1%2C%20v2%2C%20options)%20%7B%5Cn%20%20if(v1%20%3D%3D%3D%20v2)%20%7B%5Cn%20%20%20%20return%20options.fn(this)%3B%5Cn%20%20%7D%5Cn%20%20return%20options.inverse(this)%3B%5Cn%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.0.12%22%7D

# Question

hi, thanks for the help

I have several days trying to load this Helper in my app ... but it always gives me an error, like "Handlebars is not defined" or "Handlebars is not defined" [  when I add the line    "var handlebars = require ('express-handlebars');"           ]

As you will see, I am a newbie, I do not know how or where to place the Helpers
![Screenshot_56](https://user-images.githubusercontent.com/92663525/137615037-dfc719d5-8833-424c-bb90-1bbe6a4d174b.jpg)
![helpers](https://user-images.githubusercontent.com/92663525/137615205-0c46fc1f-5b66-49f1-b0c5-6f96a9bb7881.jpg)

**Comment by jaylinski** [comment]
@Amlleluzzz Please ask in the https://github.com/express-handlebars/express-handlebars project.
