### ISSUE TITLE
[Bug] No errors are thrown for {{no.input}}

### ISSUE THREAD

**Issue by Mohsen-Bazmi** [handlebars-lang/handlebars.js#1770]
The following template with no inputs
````handlebars
    Handlebars.compile('{{a.b}}')()
````
Should throw error, but it doesn't.

Steps to reproduce:
1 - Open [this](https://jsfiddle.net/aL10pum7/2/) fiddle.
2 - Open the fiddle's console.
3 - Run
4 - Errors should be thrown, but no errors are logged on the console.
5 - Change `{{a.b}}` to `{{a. b}}`
6 - The error appears.

Unit test: https://jsfiddle.net/aL10pum7/4/

**Comment by jaylinski** [comment]
@Mohsen-Bazmi Thanks for your report, but this is working as intended. In order to get exceptions for missing data, you have to activate the strict-mode:

```js
template = Handlebars.compile('{{a.b}}', { strict: true });
template({});
```
