### ISSUE TITLE
Something weird with #each when there is only one element in array

### ISSUE THREAD

**Issue by lukasz-dusza** [handlebars-lang/handlebars.js#1796]
Hello,
I have a problem with #each and parent context when there is only one element in array.

I have following data:
`{"items": [{"name":"Parent 1","childrenItems":{"1":["1", "2"],"2":["2"],"3":["3"],"4":["4"],"5":["5"],"6":["6"]}},{"name":"Parent 2","childrenItems":{"1":["11","12","13","14","15","16","17","18","19"],"2":["20"],"3":["1"]}}]}`

and following HTML:
![image](https://user-images.githubusercontent.com/25982161/146809755-4ca9d56f-232c-4a39-87ad-dfe670ed7a29.png)

And the problem is that when I have only one element in my nested array I don't have access to {{../../name}} and generally there is something wrong with parent context. I had to update handlebars version and I see that this problem occurs from version 4.0.6.
![image](https://user-images.githubusercontent.com/25982161/146809785-c86f0da8-5c20-4520-a7b6-e4be31a69dff.png)

Is this some bug or should I change something in this code, data structure?

**Comment by jaylinski** [comment]
@lukasz-dusza Possibly related to #1300. Can you check if the workaround (https://github.com/handlebars-lang/handlebars.js/issues/1300#issuecomment-318171826) helps?

**Comment by lukasz-dusza** [comment]
@jaylinski maybe this is not 100% from comment that you linked but after using {{#with}} I can achieve what I was expecting, so big thanks for showing me this tip.

![image](https://user-images.githubusercontent.com/25982161/146819859-ca4df3e8-dfb3-406e-917c-43171e1889c4.png)
![image](https://user-images.githubusercontent.com/25982161/146819889-99af73fa-c550-48f5-b5dd-44a3be81e329.png)
