### ISSUE TITLE
Code coverage numbers not getting generated when using newer version of handlebars

### ISSUE THREAD

**Issue by jdeepak14** [handlebars-lang/handlebars.js#1807]
Hi,

With handlebars 4.5.3 code coverage numbers get generated just fine but with handlebars 4.7.7 they stop getting generated. 

For security reasons the higher version is recommended but due to this issue we have not yet been able to upgrade to it.

Please suggest what can be done. 

Thanks and Regards

Deepak

**Comment by jaylinski** [comment]
@jdeepak14 Can you provide a working example on how you generate code-coverage with handlebars 4.5.3? (It will help me to debug the issue.)

Related to #1780.

**Comment by jdeepak14** [comment]
Sorry for the late reply. I was away from work.

The application code in question is written in NodeJS and given below is the command we use to generate code coverage.

./node_modules/.bin/_mocha -- --recursive test/*Tests.js -R xunit -O output=./build/test-results/test/coverage-reports.xml --exit 

Here are the versions we use of some of the relevant node modules. 

    "istanbul": "1.1.0-alpha.1",
    "mocha": "^9.0.3",
    "nock": "^9.0.0",
    "sinon": "^7.2.3",
    "request": "^2.87.0",
    "should": "^5.2.0",
    "supertest": "^6.1.4"

**Comment by jaylinski** [comment]
@jdeepak14 Can you be more specific? How do you load handlebars templates? Do you precompile templates?

A repository with a working example would help me a lot.

**Comment by jdeepak14** [comment]
No we don't. We do not refer to handlebars directly. My understanding is it is being indirectly referenced by mocha or one of the other third parties we are directly using in the coverage command. We just do npm install to load all the node modules and then run the coverage command.

**Comment by jdeepak14** [comment]
I got some more information and hope this helps. 

You can see that in our coverage command we are using istanbul. 

Now istanbul uses instanbul-api which then uses istanbul-reports which then uses handlebars. 

That's how handlebars comes into play for us and it's version makes all the difference between coverage generation succeeding and failing while keeping the versions of all other libraries just the same.

**Comment by jaylinski** [comment]
Ok, so you are not directly using handlebars but only through a 3rd-party dependency?

In this case I would suggest to update your dev-dependencies to the latest version.
Use [`nyc`](https://github.com/istanbuljs/nyc) instead of `istanbul`. This will use `istanbul-reports` v3, which does not rely on handlebars anymore: https://github.com/istanbuljs/istanbuljs/pull/503
