### ISSUE TITLE
@../index in double loop is incorrect.

### ISSUE THREAD

**Issue by leedavi** [handlebars-lang/handlebars.js#1832]
I have a handlebars template like this......  (complex data)

    {{#each genxml.data.genxml.rows.genxml}}
    {{#each imagelist.genxml}}
    {{#if @first}}

    <div id="sliderind{{moduleref @root}}-{{@index}}" onclick="changebanner{{moduleref @root}}({{@index}});" class="w3-row">
        <img class="sliderind{{moduleref @root}}" src="{{image @root "thumburl" @../index @index @root.genxml.remotemodule.genxml.settings.width @root.genxml.remotemodule.genxml.settings.height}}" style="width: 100%;">
        <div class="w3-display-middle w3-center">
            {{#imagetest @root "hasheading" @../index @index}}
            <h2 class="">{{image @root "alt" @../index @index}}</h2>
            {{/imagetest}}
            {{#imagetest @root "hassummary" @../index @index}}
            <h3 class="">{{image @root "summary" @../index @index}}</h3>
            {{/imagetest}}
            {{#imagetest @root "haslink" @../index @index}}
            <div class="w3-button">
                <a href="{{image @root "url" @../index @index}}" class="w3-text-light-grey" style="text-decoration:none;">{{image @root "urltext" @../index @index}}</a>
            </div>
            {{/imagetest}}
        </div>
    </div>

    {{else}}

    <div id="sliderind{{moduleref @root}}-{{@index}}" onclick="changebanner{{moduleref @root}}({{@index}});" class="w3-row" style="display:none;">
        <img class="sliderind{{moduleref @root}}" src="{{image @root "thumburl" @../index @index @root.genxml.remotemodule.genxml.settings.width @root.genxml.remotemodule.genxml.settings.height}}" style="width: 100%;">
        <div class="w3-display-middle w3-center">

            <span>@../index: {{@../index}}</span>

            {{#imagetest @root "hasheading" @../index @index}}
            <h2 class="">{{image @root "alt" @../index @index}}</h2>
            {{/imagetest}}
            {{#imagetest @root "hassummary" @../index @index}}
            <h3 class="">{{image @root "summary" @../index @index}}</h3>
            {{/imagetest}}
            {{#imagetest @root "haslink" @../index @index}}
            <div class="w3-button">
                <a href="{{image @root "url" @../index @index}}" class="w3-text-light-grey" style="text-decoration:none;">{{image @root "urltext" @../index @index}}</a>
            </div>
            {{/imagetest}}
        </div>
    </div>

    {{/if}}

    {{/each}}
    {{/each}}

Because of the completed data I created a #imagetest helper (in c#), if does this...

                    if (img.Alt != "")
                        options.Template(writer, (object)context);
                    else
                        options.Inverse(writer, (object)context);

This @first loop works OK for everything.  And the test itself works.  However on the second call of the helper  {{image @root "alt" @../index @index}}.

The @../index no longer is the parent loop it is the @index value.

**Comment by leedavi** [comment]
I think maybe this could be a HandlebarsDotNet.Handlebars problem?

**Comment by jaylinski** [comment]
@leedavi If you are parsing your handlebars templates with a .NET library, this is the wrong repository.

**Comment by leedavi** [comment]
OK thx.  I thought that after I posted.
