### ISSUE TITLE
Make Handlebars work with the shadow dom

### ISSUE THREAD

**Issue by simonfile** [handlebars-lang/handlebars.js#1846]
Please could you enhance your excellent library to work with the shadow dom.  We are developing a solution using web components / custom elements (via LIT).  Unfortunately Handlebars does not seem to work / render - presumably because of the shadow dom.

**Comment by jaylinski** [comment]
Why do you need handlebars when you are using `lit-html`?

Also: an example would be helpful.

**Comment by jaylinski** [comment]
@simonfile I still don't know why you are trying to use handlebars when you could just use `lit-html` for rendering HTML:

https://lit.dev/docs/libraries/standalone-templates/

Why do you need handlebars?
