### ISSUE TITLE
Dependency minimist (v1.2.6) seems to be vulnerable, any plans on fixing this?

### ISSUE THREAD

**Issue by blaasvaer** [handlebars-lang/handlebars.js#1882]
Before filing issues, please check the following points first:

- [ ] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Have a look at https://github.com/handlebars-lang/handlebars.js/blob/master/CONTRIBUTING.md
- [ ] Read the FAQ at https://github.com/handlebars-lang/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

**Comment by jaylinski** [comment]
You have to update this dependency in your own project.

See https://github.com/handlebars-lang/handlebars.js/issues/1845, https://github.com/handlebars-lang/handlebars.js/pull/1879, https://github.com/handlebars-lang/handlebars.js/pull/1877 and https://github.com/handlebars-lang/handlebars.js/pull/1841#issuecomment-1074883027.

Duplicate of https://github.com/handlebars-lang/handlebars.js/issues/1851.

**Comment by blaasvaer** [comment]
Not possible, as no option to update nested deps in npm exists as far as I've able to research. Not going to manually override deeply nested deps in separate file as we've got plenty on hour hands just managing packages themselves. Need a package manager with better architecture.

**Comment by jaylinski** [comment]
Just remove and re-add your handlebars-dependency and your lock-file will be updated with the latest (and patched) minimist dependency.
