### ISSUE TITLE
Broken Link on NPM Docs

### ISSUE THREAD

**Issue by rogadev** [handlebars-lang/handlebars.js#1918]
If you navigate to the [npm docs for handlebars](https://www.npmjs.com/package/handlebars) you'll notice that the first link under "Usage" to the Mustache Man website is broken.

"Usage
In general, the syntax of Handlebars.js templates is a superset of Mustache templates. For basic syntax, check out the [**_Mustache manpage_**](http://mustache.github.com/mustache.5.html)."

The link used is:
http://mustache.github.com/mustache.5.html

What it should be is:
http://mustache.github.io/mustache.5.html

I'm not sure if I could have made the edit myself directly. I didn't see the same issue in your GitHub readme. So I assume it's pulling from a different readme file. Hope this helps!

**Comment by jaylinski** [comment]
This was already fixed in our `master`-branch, but not yet released as npm-package.

We should probably backport those fixes to the 4.x branch and release a new version.

**Comment by rogadev** [comment]
@jaylinski For my own future reference, where do the docs live that would reflect a change to the npm documentation? And is that where most people save them? I've never uploaded my own npm package before so I'm not familiar with the process.

**Comment by jaylinski** [comment]
@rogadev npmjs.com simply displays the README.md file. Or more specifically, the file defined here:
https://github.com/handlebars-lang/handlebars.js/blob/v4.7.7/package.json#L19

**Comment by eerison** [comment]
> @rogadev npmjs.com simply displays the README.md file. Or more specifically, the file defined here: https://github.com/handlebars-lang/handlebars.js/blob/v4.7.7/package.json#L19

if it was fixed in version 4.7.7, then I guess this issue could be closed? 👀
