### ISSUE TITLE
Urgent: Potential Security Vulnerability Identified in Recent Package

### ISSUE THREAD

**Issue by RahatFatimah** [handlebars-lang/handlebars.js#1959]
Dear Team,

I trust you are all in good health. I am writing to inform you about a possible security vulnerability that I've come across in the package we installed recently. A vulnerability scan of the lock file, using Vulert, has revealed the presence of over 33 dependencies that may be vulnerable.

Given the serious security implications this could have for our project, I am uncertain of the correct procedure to follow for responsible disclosure. It's worth noting that even though some of these dependencies are limited to development, they remain in the lock file and might appear in the vendor folder, so managing them properly is of utmost importance.

To better understand the situation, please review the vulnerability scan report of the package-lock file at this URL: https://vulert.com/vuln-scan/list/5df733a4-c357-41f6-9ec5-f690a9b74486

I strongly recommend that we act promptly to address these vulnerabilities to ensure our project's security. If you require more details or further explanation, please feel free to reach out to me.

You can find the scanned lock file at this location: https://github.com/handlebars-lang/handlebars.js/blob/master/package-lock.json

I look forward to your immediate attention and response on this matter.

Kind regards.

**Comment by jaylinski** [comment]
Thanks for reporting. We are aware that our lock-file contains outdated dependencies.

We are also aware that when running `npm install handlebars`, no vulnerable dependencies are installed.

#### Proof

```
→ npm install handlebars

added 6 packages in 1s

1 package is looking for funding
  run `npm fund` for details
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 

→ npm audit
found 0 vulnerabilities
```
