### ISSUE TITLE
vulnerable version of uglify-js: 3.1.4

### ISSUE THREAD

**Issue by galens** [handlebars-lang/handlebars.js#2018]
Before filing issues, please check the following points first:

- [ ] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars

Hello, I see this first point, but the link is broken, it's not clear to me where this should be reported.

uglify-js package versions before 3.14.3 are vulnerable to Regular Expression Denial of Service (ReDoS) via minify() function that uses vulnerable regex.

appears to be fixed in 3.14.3

**Comment by jaylinski** [comment]
Thanks for letting us know! We already allow every version of uglify-js `v3` in the latest handlebars release, including the patched uglify-js version:

```
"uglify-js": "^3.1.4"
```

Related to https://github.com/handlebars-lang/handlebars.js/issues/1904, #1882, https://github.com/handlebars-lang/handlebars.js/issues/1845, https://github.com/handlebars-lang/handlebars.js/pull/1879, https://github.com/handlebars-lang/handlebars.js/pull/1877 and https://github.com/handlebars-lang/handlebars.js/pull/1841#issuecomment-1074883027.

Vulnerability: https://security.snyk.io/vuln/SNYK-JS-UGLIFYJS-1727251
