### ISSUE TITLE
Content Security Policy is blocking the handlebars.js script in dist/handlebars.js

### ISSUE THREAD

**Issue by BalkrishnaBhat** [handlebars-lang/handlebars.js#2033]
Handlebar widget in Apache Superset is not working when Content security policy is applied. This is because, handlebars.js scrip has Function.apply code which is not acceptable.
In version 4.7.7, this code is at line 4135 ('return Function.apply(this, params);')

![Untitled](https://github.com/handlebars-lang/handlebars.js/assets/8862548/9f94dc9d-6048-4ae8-9ff9-51269edcc7b3)

If we set script-src to unsafe-eval, it works but unsafe-eval is not a recommended option for production system. 

Is there a alternate way to handle this OR if there is any plan to resolve this in upcoming version

Thanks!!

**Comment by jaylinski** [comment]
This is a known issue. See issue #1934 for more information and workarounds.
