### ISSUE TITLE
Parent height is incorrect if child has break-inside: avoid 

### ISSUE THREAD

**Issue by jurikonradi** [handlebars-lang/handlebars.js#2057]
Parent height in HTML is not recalculated when child's div is sent to next PDF page. Parent height is the same as if child would be on its original position (without break-inside: avoid)

![handlebars break-inside problem](https://github.com/user-attachments/assets/dd8c02c5-800b-4a3e-814e-875adcc9a132)

**Comment by jaylinski** [comment]
Are you trying to report an issue with handlebars or is this a question?

**Comment by jurikonradi** [comment]
This is issue, but probably due to overcomplicated html code i was triyng to fix. I think it was generated by some script with a lot of nested tables. I rewrote it, and seems that this issue is gone. I will remove this bug report on Monday, need more testing.With best wishes, Juri.On 30 Nov 2024, at 19:22, Jay Linski ***@***.***> wrote:﻿
Are you trying to report an issue with handlebars or is this a question?
